### ISSUE TITLE
How can i obfuscate my script?

### ISSUE THREAD

**Issue by top1stash** [Luraph/luraph-vscode#3]
How can i obfuscate my script via visual studio code?

**Comment by memcorrupt** [comment]
@top1stash 

> To obfuscate, open the file to be obfuscated, and then click on the Obfuscate with Luraph item in the status bar at the bottom of the window or use the Luraph: Obfuscate File command. That's it!
<sub>source: https://github.com/Luraph/luraph-vscode?tab=readme-ov-file#usage</sub>
